Akeneo\Tool\Bundle\ApiBundle\Entity\AuthCode:
    type: entity
    table: pim_api_auth_code
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        token:
            type: string
            length: 255
            unique: true
        redirectUri:
            column: redirect_uri
            type: string
            length: 255
            nullable: true
        expiresAt:
            column: expires_at
            type: integer
            nullable: true
        scope:
            type: string
            length: 1000
            nullable: true
    manyToOne:
        client:
            targetEntity: Akeneo\Tool\Bundle\ApiBundle\Entity\Client
            joinColumns:
                client_id:
                    referencedColumnName: id
                    onDelete: CASCADE
        user:
            targetEntity: Akeneo\UserManagement\Component\Model\User
            joinColumns:
                user_id:
                    referencedColumnName: id
                    onDelete: CASCADE
