Akeneo\Tool\Bundle\ApiBundle\Entity\Client:
    type: entity
    table: pim_api_client
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        randomId:
            column: random_id
            type: string
            length: 255
            nullable: true
        secret:
            type: string
            length: 255
            nullable: true
        redirectUris:
            column: redirect_uris
            type: array
            nullable: true
        allowedGrantTypes:
            column: allowed_grant_types
            type: array
            nullable: true
        label:
            type: string
            length: 255
            nullable: true
        marketplacePublicAppId:
            column: marketplace_public_app_id
            type: string
            length: 255
            nullable: true
