Akeneo\Tool\Bundle\ApiBundle\Entity\RefreshToken:
    type: entity
    table: pim_api_refresh_token
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        token:
            type: string
            length: 255
            unique: true
        expiresAt:
            column: expires_at
            type: integer
            nullable: true
        scope:
            type: string
            length: 1000
            nullable: true
    manyToOne:
        user:
            targetEntity: Akeneo\UserManagement\Component\Model\UserInterface
            joinColumns:
                user:
                    referencedColumnName: id
                    onDelete: CASCADE
        client:
            targetEntity: Akeneo\Tool\Bundle\ApiBundle\Entity\Client
            joinColumns:
                client:
                    referencedColumnName: id
                    onDelete: CASCADE
